development:
  adapter: postgresql
  database: blablas_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: blablas_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: blablas_production
  pool: 5
  timeout: 5000
